package protocol.request;

public interface RequestOperations {
    String LOGIN = "LOGIN";
    String LOGOUT = "LOGOUT";
    String ADMIN_BUSCAR_USUARIOS = "ADMIN_BUSCAR_USUARIOS";
    String ADMIN_BUSCAR_USUARIO = "ADMIN_BUSCAR_USUARIO";
    String ADMIN_CADASTRAR_USUARIO = "ADMIN_CADASTRAR_USUARIO";
    String ADMIN_ATUALIZAR_USUARIO = "ADMIN_ATUALIZAR_USUARIO";
    String ADMIN_DELETAR_USUARIO = "ADMIN_DELETAR_USUARIO";
    String BUSCAR_USUARIO = "BUSCAR_USUARIO";
    String CADASTRAR_USUARIO = "CADASTRAR_USUARIO";
    String ATUALIZAR_USUARIO = "ATUALIZAR_USUARIO";
    String DELETAR_USUARIO = "DELETAR_USUARIO";

    String CADASTRAR_PDI = "CADASTRAR_PDI";
    String BUSCAR_PDIS = "BUSCAR_PDIS";
    String ATUALIZAR_PDI = "ATUALIZAR_PDI";
    String DELETAR_PDI = "DELETAR_PDI";
    String CADASTRAR_SEGMENTO = "CADASTRAR_SEGMENTO";
    String BUSCAR_SEGMENTOS = "BUSCAR_SEGMENTOS";
    String ATUALIZAR_SEGMENTO = "ATUALIZAR_SEGMENTO";
    String DELETAR_SEGMENTO = "DELETAR_SEGMENTO";


}
